### ISSUE TITLE
I can't shoot any lazers

### ISSUE THREAD

**Issue by xhp-creations** [vgmoose/space#10]
The spacship flies around and around, but I just can't shoot the enemies.  Why can't you shoot with the right-stick or something?  That would be awesome.

**Comment by vgmoose** [comment]
You can touch the screen to shoot. Commit https://github.com/vgmoose/space/commit/c285ff4e12e6513fee3bbf38d5e00c85f2da6305 adds a reminder about using the touchpad to shoot, if you haven't yet.

Someone I know has made a [right-stick to shoot control scheme here](https://github.com/xhp-creations/space/commit/d6a592bf0965804cb048dc1880efd7e9e9d901f7). I hope to have it integrated soon!
