### ISSUE TITLE
Sound in RPX

### ISSUE THREAD

**Issue by vgmoose** [vgmoose/space#20]
In the wut branch, the RPX needs sound!

This would preferably be done via a content/ folder rather than by being embedded into the RPX

**Comment by CreeperMario** [comment]
In a similar fashion to how mods can be loaded automatically thanks to @dimok789's resource library, this would once again allow modding, haxchi style.

Question: Now that RPX files can be launched within HBL, is it necessary to maintain the HBL ELF build now? The RPX file can be launched from HBL, Loadiine GX2 and the Wii U Menu, and probably our emulators as well.

**Comment by CreeperMario** [comment]
Done. See the wut_working branch.
(There is a small bug that causes it to say it is 49 commits behind the hbl_elf branch, because I created the wut_working branch as an orphan, with no history imported from the hbl_elf branch.)
